alias ll='ls -lah'
alias histgrep='history | grep'
alias apt='sudo $(which apt)'
alias reboot='sudo $(which reboot)'
alias halt='sudo $(which alias)'
alias poweroff='sudo $(which poweroff)'
alias grep='grep --color'
alias hgrep='grep --color=always -e "^" -e '
alias negrep='grep --color=always -e "^" -e "E:" | grep --color=always -e "^" -e "W:" | grep --color=always -i "error\|warning\|problem\|fail\|fatal\|panic\|not found\|missing\|could not"'
