#!/bin/bash
#
# This is an sdm plugin for: mydotfiles.  This installs my dot files to my home directory.
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#
function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}
#
# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
loadparams && DEBUG=${custom1:-0}
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
#
plugin_getargs $pfx "$args" "|assetDir|"
[ -f $SDMPT/etc/sdm/assets/common.sh ] || cp -va $assetDir/common.sh $SDMPT/etc/sdm/assets/common.sh
source $SDMPT/etc/sdm/assets/common.sh
fDebugLog 3 "Sucessfully sourced $SDMPT/etc/sdm/assets/common.sh" wait

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Start Phase 0"
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Copying plugin-assets to image"
    cp -av --reflink=auto $assetDir/ $SDMPT/etc/sdm/assets/myassets
    #
    plugin_dbgprint "renamepi=$renamepi    myuser=$myuser"
    [ $DEBUG -ge 5 ] && fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." && read -n 1 -s -r
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Complete Phase 0" wait

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Start Phase 1"
    #logfreespace "at start of Plugin $pfx Phase 1"
    #
    #logfreespace "at end of $pfx Phase 1"
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Complete Phase 1" wait
else
    #
    # Plugin Post-install edits
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Start Phase post-install"
    #logfreespace "at start of Plugin $pfx Phase post-install"
    
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Copying .bash_aliases > home directory"
    cp -av --reflink=auto $SDMPT/etc/sdm/assets/myassets/.bash_aliases $SDMPT/home/$myuser/
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Copying .bashrc > home directory"
    cp -av --reflink=auto $SDMPT/etc/sdm/assets/myassets/.bashrc $SDMPT/home/$myuser/
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Creating directory ~/.ssh/"
    mkdir -vp $SDMPT/home/$myuser/.ssh/
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Copying .ssh/ > home directory"
    cp -av --reflink=auto $SDMPT/etc/sdm/assets/myassets/{authorized_keys,known_hosts,id_ed25519.pub} $SDMPT/home/$myuser/.ssh/
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Copying .local/ > home directory"
    cp -av --reflink=auto $SDMPT/etc/sdm/assets/myassets/.local/ $SDMPT/home/$myuser/.local/
    #
    plugin_dbgprint "renamepi=$renamepi    myuser=$myuser"
    [ $DEBUG -ge 5 ] && fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." && read -n 1 -s -r
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Complete Phase 0"
    #
    #logfreespace "at end of $pfx Custom Phase post-install"
    [ $DEBUG -ge 5 ] && fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." && read -n 1 -s -r
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Complete Phase post-install" wait
fi
