#!/bin/bash
#
# This is an sdm plugin for: btfix.  This stops the blutooth.service from loading the sap driver
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#
function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}
# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
loadparams && DEBUG=${custom1:-0}
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
#
plugin_getargs $pfx "$args" "|assetDir|"
[ -f $SDMPT/etc/sdm/assets/common.sh ] || cp -va $assetDir/common.sh $SDMPT/etc/sdm/assets/common.sh
source $SDMPT/etc/sdm/assets/common.sh
fDebugLog 3 "Sucessfully sourced $SDMPT/etc/sdm/assets/common.sh" wait
#
if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Start Phase 0" wait
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    #
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Creating directory bluetooth.service.d/" 
    mkdir -pv $SDMPT/etc/systemd/system/bluetooth.service.d/
    #
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Copying $assetDir/override.conf > $SDMPT/etc/systemd/system/bluetooth.service.d/override.conf"
    cp -av --reflink=auto $assetDir/override.conf $SDMPT/etc/systemd/system/bluetooth.service.d/override.conf
    #
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Complete Phase 0"
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." wait
    #
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Start Phase 1"
    #logfreespace "at start of Plugin $pfx Phase 1"
    #
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." wait
    #
    #logfreespace "at end of $pfx Phase 1"
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Start Phase post-install"
    #logfreespace "at start of Plugin $pfx Phase post-install"
    #
    fDebugLog 2 "* Plugin $pfx. DEBUG $DEBUG: Nothing to do"
    #
    #logfreespace "at end of $pfx Custom Phase post-install"
    fDebugLog 3  "* Plugin $pfx. DEBUG $DEBUG: Complete Phase post-install" wait
fi
