#!/bin/bash
#
# This is an sdm plugin for: enablenetfwd.  This enables net.ipv4.ip_forward and /net.ipv6.conf.all.forwarding in sysctl.conf
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
source $SDMPT/etc/sdm/sdm-readparams
#
DEBUG=${custom1:-0} && LOGPREFIX=${custom2:-"*Plugin*-${(basename $0)%%.*}"}
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
#
plugin_getargs $pfx "$args" "|assetDir|"
[ -f $SDMPT/etc/sdm/assets/common.sh ] || cp -va $assetDir/common.sh $SDMPT/etc/sdm/assets/common.sh
source $SDMPT/etc/sdm/assets/common.sh
fDebugLog 3 "Sucessfully sourced $SDMPT/etc/sdm/assets/common.sh" wait
#
if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    fDebugLog 1 "* Plugin $pfx: Start Phase 0"
    fDebugLog 3 "$(plugin_printkeys)"
    #
    fDebugLog 2 "* Plugin $pfx: Enabling net forward."
    cp -av --reflink=auto $SDMPT/etc/sysctl.conf $SDMPT/etc/sysctl.conf.orig  
    cat $SDMPT/etc/sysctl.conf | \
        sed 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' | \
        sed 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/g' \
        | tee $SDMPT/etc/sysctl.conf
    #
    fDebugLog 1 "* Plugin $pfx: Complete Phase 0" wait
    #
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    fDebugLog 1 "* Plugin $pfx: Start Phase 1 (in nspawn)"
    fDebugLog 3 "$(plugin_printkeys)"
    #
    fDebugLog 2 "* Plugin $pfx: Enabling net forward."
    cp -av --reflink=auto $SDMPT/etc/sysctl.conf $SDMPT/etc/sysctl.conf.orig  
    cat $SDMPT/etc/sysctl.conf | \
        sed 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' | \
        sed 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/g' \
        | tee $SDMPT/etc/sysctl.conf
    #
    fDebugLog 1 "* Plugin $pfx: Complete Phase 1" wait
    #
else
    #
    # Plugin Post-install edits
    #
    fDebugLog 1 "* Plugin $pfx: Start Phase post-install"
    fDebugLog 3 "$(plugin_printkeys)"
    #
    fDebugLog 2 "* Plugin $pfx: Nothing to do"
    #
    fDebugLog 1 "* Plugin $pfx: Complete Phase post-install" wait
    #
fi
