#!/bin/bash
#
# This is an sdm plugin for: pxehost.  This configures my git environment.
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#
function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}
# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
loadparams && DEBUG=${custom1:-0}
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx. DEBUG $DEBUG: Start Phase 0"
    [ $DEBUG -ge 5 ] && logtoboth "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." && read -n 1 -s -r
    logtoboth "* Plugin $pfx. DEBUG $DEBUG: Complete Phase 0"
    #
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    plugin_getargs $pfx "$args" "|netIface|ipAddr|dnsaddr|brdAddr|gwAddr|dhcpRange|tftpRootDir|nfsRootDir!"
    plugin_printkeys

    logtoboth "* Plugin $pfx. DEBUG $DEBUG: Start Phase 1"
    logfreespace "at start of Plugin $pfx Phase 1"
    #
    logtoboth "> Plugin $pfx: Install dnsmasq & nfs-kernel-server"
    doaptrpterror "install --no-install-recommends -y dnsmasq nfs-kernel-server" "${showapt}"
    #
    logfreespace "at end of $pfx Phase 1"
    #
    [ $DEBUG -ge 5 ] && logtoboth "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." && read -n 1 -s -r
    logtoboth "* Plugin $pfx. DEBUG $DEBUG: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx. DEBUG $DEBUG: Start Phase post-install"
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    #logfreespace "at start of Plugin $pfx Phase post-install"
    #
    #logfreespace "at end of $pfx Custom Phase post-install"
    [ $DEBUG -ge 5 ] && logtoboth "* Plugin $pfx. DEBUG $DEBUG: Press any key to continue..." && read -n 1 -s -r
    logtoboth "* Plugin $pfx. DEBUG $DEBUG: Complete Phase post-install"
fi
