#!/usr/bin/env bash
#
set -e
#
function pluginHelp(){
    cat <<EOF 1>&2

This is an sdm plugin for: ${me}.  This is a test plugin to experiment with code.

The plugin is called three times: for Phase 0 (Mounted environment), Phase 1 (in nspawn), and Phase 2 (post-install).
'\$1' is the phase: "0", "1", or "post-install"
'\$2' is the argument list: arg1=val1|arg2=val2|arg3=val3| ...4

Valid arguments to this plugin are:-
    assetDir    -   Directory where local assets such as common.sh are stored.

EOF
}
#
# Main code for the Plugin
#
phase=${1}
me="$(basename ${0})"
pfx="${me} Phase ${phase}"     #For messages
args="${2}"
#
# Check that phase is set to check if we are running within sdm.  If not set 
# or set to help, then display help text & exit.
#
#[[ -z ${phase} ]] || [[ ${phase} =~ help ]] && pluginHelp && exit 0
[[ ! "0 1 post-install" =~ (^| )${phase}($| ) ]] && pluginHelp && exit 0
#
source $SDMPT/etc/sdm/sdm-readparams
plugin_getargs "$me" "$args" "|assetDir|DEBUG|LOGPREFIX|"
#
copiedCommon=0
if ! [ -f $SDMPT/etc/sdm/local-assets/common.sh ] 
then
    copiedCommon=1
    cp -av $assetDir/common.sh $SDMPT/etc/sdm/local-assets/common.sh && copiedCommon=3
fi
#
source $SDMPT/etc/sdm/local-assets/common.sh || exit 1
fDebugLog 2 "* Plugin $pfx: Sucessfully sourced $SDMPT/etc/sdm/local-assets/common.sh copiedCommon=${copiedCommon}" yesno
#
if [[ "$phase" == "0" ]]
then
    #
    # In Phase 0 (Mounted environment) all references to directories in the image must be preceded by $SDMPT
    #
    fDebugLog 1 "* Plugin $pfx: Start Phase."
    fDebugLog 3 "$(plugin_printkeys)"
    #
    fDebugLog 2 "Plugin $pfx: Setting up k3s."
#    fDebugLog 2 "Plugin $pfx: Running curl to get gpg key for pimoz repository" 
#    curl https://raw.githubusercontent.com/pimox/pimox7/master/KEY.gpg | gpg --dearmo | tee $SDMPT/etc/apt/trusted.gpg.d/pimox.gpg
#    fDebugLog 2 "Plugin $pfx: Done setting up k3s in Phase 0 (Mounted environment)" wait 4
    #
#    fDebugLog 2 "Plugin $pfx: Configuring $SDMPT/boot/cmdline.txt"
#    if [ "$(cat $SDMPT/boot/cmdline.txt | grep cgroup)" != "" ]
#    then
#        fDebugLog 2 "Plugin $pfx: Seems to be already configured!"
#    else
#        sed -i "1 s|$| cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1|" $SDMPT/boot/cmdline.txt
#    fi
#    fDebugLog 2 "Plugin $pfx: Done configuring $SDMPT/boot/cmdline.txt" wait 4
    fDebugLog 1 "* Plugin $pfx: Complete Phase." yesno
    #
elif [[ "$phase" == "1" ]]
then
    #
    # Phase 1 (in nspawn)
    #
    fDebugLog 1 "* Plugin $pfx: Start Phase."
    fDebugLog 3 "$(plugin_printkeys)"
    #
    fDebugLog 2 "Plugin $pfx: Nothing to do."
    #
    fDebugLog 1 "* Plugin $pfx: Complete Phase." yesno
    #
else
    #
    # Plugin Phase 2 (post-install) edits
    #
    fDebugLog 1 "* Plugin $pfx: Start Phase."
    fDebugLog 3 "$(plugin_printkeys)"
    #    
    fDebugLog 2 "Plugin $pfx: Nothing to do."
    #
    fDebugLog 1 "* Plugin $pfx: Complete Phase." yesno
fi
